pipeline {
    agent any

parameters {
    string(name: 'PYTHON_PATH', defaultValue: '~/Library/Python/2.7/bin/', description: 'Python')
}

stages{
        stage('Validate CFN template'){
            steps {
                echo 'Vaidating template'
                sh "${params.PYTHON_PATH}aws cloudformation validate-template --template-body file:///Users/hoa/code/cloudformation/very_sample1.json"
            }
            post {
                success {
                    echo 'CFN has been validated successfully!'
                }
            }
        }

        stage('Deploy CFN stack'){
            steps {
                echo 'Building stack'
                sh "${params.PYTHON_PATH}aws cloudformation create-stack --stack-name myteststack --template-url https://s3-ap-southeast-2.amazonaws.com/cf-templates-1v98k5s74tmkv-ap-southeast-2/2018142hUu-very_sample1.json"
            }
            post {
                success {
                    echo 'CFN stack creation completed successfully!'
                }
            }
        }

    }
}
