pipeline {
    agent any

parameters {
    string(name: 'PYTHON_PATH', defaultValue: '~/Library/Python/2.7/bin/', description: 'Where Jenkins user sees Python')
    string(name: 'CFN_STACK_NAME', defaultValue: 'myStack', description: 'CFN stack name')
    string(name: 'CFN_TEMPLATE_URL', defaultValue: 'https://s3-ap-southeast-2.amazonaws.com/cf-templates-1v98k5s74tmkv-ap-southeast-2/2018142hUu-very_sample1.json', description: 'CFN S3 template URL')
}

stages{
        stage('Validate CFN template'){
            steps {
                echo 'Vaidating template'
                sh "${params.PYTHON_PATH}aws cloudformation validate-template --template-body ${params.CFN_TEMPLATE_URL}"
            }
            post {
                success {
                    echo 'CFN has been validated successfully!'
                }
            }
        }

        stage('Deploy CFN stack'){
            steps {
                echo 'Building stack'
                sh "${params.PYTHON_PATH}aws cloudformation create-stack --stack-name ${params.CFN_STACK_NAME} --template-url ${params.CFN_TEMPLATE_URL}"
            }
            post {
                success {
                    echo 'CFN stack creation completed successfully!'
                }
            }
        }

    }
}
